# Generated by Django 5.0.2 on 2024-02-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('concentracion', models.CharField(max_length=200)),
                ('fecha_prod', models.CharField(max_length=200)),
                ('volumen', models.IntegerField(default=0)),
                ('unidades', models.CharField(default='ml', max_length=200)),
                ('uso', models.TextField()),
            ],
        ),
    ]
