# Generated by Django 5.0.2 on 2024-02-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('uso', models.TextField()),
            ],
        ),
    ]
