# Generated by Django 5.0.2 on 2024-02-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
