# Generated by Django 5.0.2 on 2024-02-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_material_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidades',
            field=models.CharField(default='ml', max_length=200),
        ),
    ]
