# Generated by Django 5.0.2 on 2024-02-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_marca_alter_equipo_codigo_inv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
